spring.application.name=email-writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:streamGenerateContent
gemini.api.key=AIzaSyAt8K3tPtgM8EhpIYEJqbARtkvJ03-NE6Y
server.port=8081